build_from:
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
  armv7: "ghcr.io/home-assistant/armv7-base:3.15" 
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
labels:
  org.opencontainers.image.title: "Visionect Server"
  org.opencontainers.image.description: "Visionect Server with PostgreSQL and Redis"
  org.opencontainers.image.source: "https://github.com/Adam7411/homeassistant-visionect-server"
  org.opencontainers.image.authors: "Adam7411"
args:
  TEMPIO_VERSION: "2021.09.0"
