name: "Visionect Server"
version: "7.6.5"
slug: "visionect_server"
description: "Visionect Server with PostgreSQL and Redis for e-paper displays"
url: "https://github.com/Adam7411/visionect_server"
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
ports:
  8081/tcp: 8081
  11113/tcp: 11113
ports_description:
  8081/tcp: "Web Interface"
  11113/tcp: "Server Port"
map:
  - type: shm
    description: "Shared memory"
    mode: rw
init: false
privileged: true
devices:
  - "/dev/fuse:/dev/fuse:rwm"
cap_add:
  - MKNOD
  - SYS_ADMIN
environment:
  DB2_1_PORT_5432_TCP_ADDR: postgres
  DB2_1_PORT_5432_TCP_USER: visionect
  DB2_1_PORT_5432_TCP_PASS: visionect
  DB2_1_PORT_5432_TCP_DB: koala
  REDIS_ADDRESS: redis:6379
  VISIONECT_SERVER_ADDRESS: localhost

image:
  amd64: "visionect/visionect-server-v3:7.6.5"
  armv7: "visionect/visionect-server-v3:7.6.5-arm"
  aarch64: "visionect/visionect-server-v3:7.6.5-arm"
