name: Visionect Server
version: "7.6.5"
slug: visionect_server
description: Visionect Server for Home Assistant with built-in PostgreSQL and Redis
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
map:
  - share:rw
  - config:rw
privileged: true
full_access: true
host_network: true
ports:
  8081/tcp: 8081
  11113/tcp: 11113
  5432/tcp: 5432
options:
  postgres_user: visionect
  postgres_password: visionect
  postgres_db: koala
  redis_port: 6379
schema:
  postgres_user: str
  postgres_password: str
  postgres_db: str
  redis_port: int
build_from:
  amd64: "visionect/visionect-server-v3:7.6.5"
  armv7: "visionect/visionect-server-v3:7.6.5-arm"
  aarch64: "visionect/visionect-server-v3:7.6.5-arm"
