name: "Visionect Server"
version: "7.6.5"
slug: "visionect_server"
description: "Visionect Server with PostgreSQL and Redis"
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
init: false
