name: "Visionect Server"
version: "7.6.5"
slug: visionect_server
description: "Visionect Server for Home Assistant with built-in PostgreSQL and Redis"
url: "https://github.com/Adam7411/homeassistant-visionect-server"
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
init: false
map:
  - share:rw
  - config:rw
options:
  postgres_user: visionect
  postgres_password: visionect
  postgres_db: koala
  redis_port: 6379
  image_type: auto
schema:
  postgres_user: str
  postgres_password: str
  postgres_db: str
  redis_port: int
  image_type:
    - auto
    - raspberry_pi
    - mini_pc
ports:
  8081/tcp: 8081
  11113/tcp: 11113
ports_description:
  8081/tcp: "Visionect Server Web Interface"
  11113/tcp: "Visionect Server Communication"
host_network: false
privileged: false
full_access: false
image: "ghcr.io/adam7411/homeassistant-visionect-server-{arch}"
