# Domyślna architektura (arm lub x86)
image_architecture: arm

# Adres IP serwera PostgreSQL
db_host: postgres

# Port serwera PostgreSQL
db_port: 5432

# Nazwa użytkownika bazy danych PostgreSQL
db_user: visionect

# Hasło do bazy danych PostgreSQL
db_password: visionect

# Nazwa bazy danych PostgreSQL
db_name: koala

# Adres serwera Redis
redis_host: redis

# Port serwera Redis
redis_port: 6379

# Adres serwera Visionect (domyślnie localhost)
visionect_server_address: localhost
