#!/usr/bin/with-contenv bash
echo "Waiting for PostgreSQL to be ready..."
while ! pg_isready -h 127.0.0.1 -p 5432 -U visionect -q; do
  sleep 1
done
echo "PostgreSQL is ready."
export DB2_1_PORT_5432_TCP_ADDR=127.0.0.1
export DB2_1_PORT_5432_TCP_USER=visionect
export DB2_1_PORT_5432_TCP_PASS=visionect
export DB2_1_PORT_5432_TCP_DB=koala
export REDIS_ADDRESS=127.0.0.1:6379
export VISIONECT_SERVER_ADDRESS=localhost
echo "Starting Visionect Server..."
exec /usr/local/bin/visionect-server
