# =================================================================
# OSTATECZNA, FINAŁOWA WERSJA - Z PRZYCISKIEM TRYBU OCHRONY
# =================================================================
name: "Visionect Server (all-in-one)"
version: "2.1.0" # Duża zmiana w funkcjonalności, więc nowa wersja
slug: "visionect_server_aio"
description: "Visionect Server with built-in PostgreSQL and Redis. Requires Protection Mode OFF."
url: "https://github.com/Adam7411/visionect_server"
arch:
  - "aarch64"
  - "amd64"
  - "armv7"

# === KLUCZOWA ZMIANA, KTÓRA WSZYSTKO NAPRAWIA ===
# Deklarujemy, że ten dodatek wymaga WYŁĄCZENIA Trybu Ochrony.
# To spowoduje pojawienie się przełącznika na stronie dodatku w HA.
protection: false

startup: "services"
boot: "auto"
init: false
ports:
  "8081/tcp": 8081
  "11113/tcp": 11113
ports_description:
  "8081/tcp": "Web Interface"
  "11113/tcp": "Server Port"
map:
  - "data:rw"
privileged:
  - "SYS_ADMIN"
devices:
  - "/dev/fuse"
cap_add:
  - "MKNOD"
