name: "Visionect Server (FINAL)"
version: "4.0.0" # Całkowicie nowa wersja
slug: "visionect_server_final" # <-- NOWY, UNIKALNY IDENTYFIKATOR
description: "Visionect Server with built-in PostgreSQL and Redis. Pre-built package. Requires Protection Mode OFF."
url: "https://github.com/Adam7411/visionect_server"
arch:
  - "aarch64"
  - "amd64"
  - "armv7"
protection: false
image: "adamak741/visionect-server-aio-{arch}" # Nazwa obrazu zostaje ta sama
startup: "services"
boot: "auto"
init: false
ports:
  "8081/tcp": 8081
  "11113/tcp": 11113
ports_description:
  "8081/tcp": "Web Interface"
  "11113/tcp": "Server Port"
map:
  - "data:rw"
privileged:
  - "SYS_ADMIN"
devices:
  - "/dev/fuse"
cap_add:
  - "MKNOD"
