# =================================================================
# OSTATECZNA, FINAŁOWA WERSJA - Z PRZYCISKIEM TRYBU OCHRONY
# =================================================================
name: "Visionect Server (all-in-one)"
version: "3.0.0" # Ostateczna, czysta wersja
slug: "visionect_server_aio"
description: "Visionect Server with built-in PostgreSQL and Redis. Pre-built package. Requires Protection Mode OFF."
url: "https://github.com/Adam7411/visionect_server"
arch:
  - "aarch64"
  - "amd64"
  - "armv7"

# Deklarujemy, że ten dodatek wymaga WYŁĄCZENIA Trybu Ochrony.
protection: false

# Obraz jest pobierany z Twojego Docker Huba, a nie budowany lokalnie.
# Upewnij się, że nazwa użytkownika jest poprawna.
image: "adamak741/visionect-server-aio-{arch}"

startup: "services"
boot: "auto"
init: false
ports:
  "8081/tcp": 8081
  "11113/tcp": 11113
ports_description:
  "8081/tcp": "Web Interface"
  "11113/tcp": "Server Port"
map:
  - "data:rw"
privileged:
  - "SYS_ADMIN"
devices:
  - "/dev/fuse"
cap_add:
  - "MKNOD"
