name: "Visionect Server (all-in-one)"
version: "2.0.1" # <-- JEDYNA ZMIANA
slug: "visionect_server_aio"
# ... reszta pliku bez zmian ...
description: "Visionect Server with built-in PostgreSQL and Redis. Pre-built package."
url: "https://github.com/Adam7411/visionect_server"
arch:
  - "aarch64"
  - "amd64"
  - "armv7"
# Teraz HA nie buduje obrazu, tylko go pobiera z Twojego Docker Hub
image: "adamak741/visionect-server-aio-{arch}"
startup: "services"
boot: "auto"
init: false
ports:
  "8081/tcp": 8081
  "11113/tcp": 11113
ports_description:
  "8081/tcp": "Web Interface"
  "11113/tcp": "Server Port"
map:
  - "data:rw"
privileged:
  - "SYS_ADMIN"
devices:
  - "/dev/fuse"
cap_add:
  - "MKNOD"
