name: "Visionect Server (all-in-one)"
version: "1.0.2" # Podniosłem wersję, żeby HA na pewno widział zmianę
slug: "visionect_server_aio"
description: "Visionect Server with built-in PostgreSQL and Redis. All-in-one package."
url: "https://github.com/Adam7411/visionect_server"
arch:
  - "aarch64"
  - "amd64"
  - "armv7"
startup: "services"
boot: "auto"
init: false
ports:
  "8081/tcp": 8081
  "11113/tcp": 11113
ports_description:
  "8081/tcp": "Web Interface"
  "11113/tcp": "Server Port"
map:
  - "data:rw"
privileged:
  - "SYS_ADMIN"
devices:
  - "/dev/fuse" # <-- TUTAJ JEST KLUCZOWA POPRAWKA
cap_add:
  - "MKNOD"
