name: "Hello World Test"
version: "1.0.0"
slug: "visionect_server_aio"
description: "A minimal addon to test the build process."
arch:
  - "aarch64"
  - "amd64"
  - "armv7"
startup: "once"
boot: "manual"
init: false
