name: Extract ARM Binary (Reliable Method)

on:
  workflow_dispatch:

jobs:
  extract-arm:
    name: Extract ARM binary using Crane
    runs-on: ubuntu-latest
    steps:
      - name: Pull and extract ARM image using Crane
        run: |
          echo "Pulling and exporting ARM image with crane..."
          # Używamy narzędzia 'crane', które jest znacznie bardziej niezawodne niż 'docker create'
          docker run --rm gcr.io/go-containerregistry/crane export visionect/visionect-server-v3:7.6.5-arm - | gzip > visionect_arm.tar.gz
          echo "ARM binary created."
          ls -lh visionect_arm.tar.gz

      - name: Upload ARM binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: visionect-arm-binary-final
          path: visionect_arm.tar.gz
