name: Build and Push Addon to Docker Hub

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build and Push for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ "amd64", "aarch64", "armv7" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Determine Visionect Image Tag
        id: image_tag
        run: |
          if [ "${{ matrix.arch }}" = "amd64" ]; then
            echo "tag=7.6.5" >> $GITHUB_OUTPUT
          else
            echo "tag=7.6.5-arm" >> $GITHUB_OUTPUT
          fi
      - name: Build and push addon
        uses: docker/build-push-action@v5
        with:
          context: ./visionect_server_aio
          file: ./visionect_server_aio/Dockerfile
          platforms: linux/${{ matrix.arch }}
          push: true
          # === KLUCZOWA ZMIANA, KTÓRA WSZYSTKO NAPRAWIA ===
          # Teraz wysyłamy obraz z dwiema etykietami: "latest" i "2.0.0"
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/visionect-server-aio-${{ matrix.arch }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/visionect-server-aio-${{ matrix.arch }}:2.0.0
          build-args: |
            BUILD_ARCH=${{ matrix.arch }}
            BUILD_ARCH_TAG=${{ steps.image_tag.outputs.tag }}
            BUILD_FROM=ghcr.io/home-assistant/${{ matrix.arch }}-base:latest
