name: Build and Push Addon to Docker Hub

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build Addon for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ "amd64", "aarch64", "armv7" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push addon
        uses: docker/build-push-action@v5
        with:
          context: ./visionect_server_aio
          file: ./visionect_server_aio/Dockerfile
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/visionect-server-aio-${{ matrix.arch }}:latest
          build-args: |
            BUILD_ARCH=${{ matrix.arch }}
            BUILD_FROM=ghcr.io/home-assistant/${{ matrix.arch }}-base:latest
