name: Build and Push Addon to Docker Hub

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build and Push for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ "amd64", "aarch64", "armv7" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get addon version from config.yaml (Reliable Method)
        id: addon_version
        run: |
          # Używamy 'awk' - jest to znacznie bardziej niezawodne narzędzie do parsowania tekstu.
          # Szuka on linii zaczynającej się od "version:", a następnie wyciąga tekst w cudzysłowach.
          addon_version=$(awk -F'"' '/^version:/ {print $2}' ./visionect_server_final/config.yaml)

          # Sprawdzanie błędów: Jeśli wersja jest pusta, zatrzymaj akcję z błędem.
          if [ -z "$addon_version" ]; then
            echo "Error: Could not extract version from config.yaml. Value is empty."
            exit 1
          fi
          echo "Successfully extracted version: ${addon_version}"
          echo "version=${addon_version}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Determine Visionect Image Tag
        id: image_tag
        run: |
          if [ "${{ matrix.arch }}" = "amd64" ]; then
            echo "tag=7.6.5" >> $GITHUB_OUTPUT
          else
            echo "tag=7.6.5-arm" >> $GITHUB_OUTPUT
          fi
      - name: Build and push addon
        uses: docker/build-push-action@v5
        with:
          context: ./visionect_server_final
          file: ./visionect_server_final/Dockerfile
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/visionect-server-final-${{ matrix.arch }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/visionect-server-final-${{ matrix.arch }}:${{ steps.addon_version.outputs.version }}
          build-args: |
            BUILD_ARCH=${{ matrix.arch }}
            BUILD_ARCH_TAG=${{ steps.image_tag.outputs.tag }}
